### ISSUE TITLE
Add vim compatibility

### ISSUE THREAD

**Issue by Dbz** [tksfz/doto2#9]
We already talked about this, but I'm creating an issue to track it. Once this is in, doto will be my todo list app over my current bash functions / directory / etc. setup.

**Comment by tksfz** [comment]
It's merged. Try a brew reinstall. I'll start using version numbers soon.

**Comment by Dbz** [comment]
How do I use the editor functionality?

**Comment by Dbz** [comment]
Also looking at you PR, I would suggest using vim over vi.

**Comment by tksfz** [comment]
@Dbz try `doto edit <task id>`

let me know if that's not what you were expecting
